A Better README file
snikas/react-styled-flexbox pull request #1
Opened 2018-02-25 18:48 UTC by ahmedtarek2134

I create a new documentation file because the original one had some problems, I added the following:

* A command to install the package with yarn
* A license section at the end
* The package name as a header at the start
* Fixed the wrong syntax highlighting, using html as the language is better than javascript since markdown has no JSX support.

2018-02-26 18:57 UTC, snikas commented on README.md
> +Copyright (c) 2017 Steven Akins
Please change this to Copyright (c) 2017 Raycom Media, Inc.

2018-02-26 18:59 UTC, snikas commented on README.md
> -[![Build Status](https://travis-ci.org/snikas/react-styled-flexbox.png?branch=master)](https://travis-ci.org/snikas/react-styled-flexbox)
I'd still like to show this badge. Did you mean to remove it?

2018-02-26 19:00 UTC, snikas requested changes
Thanks for the README update!
Please update the copyright line and I'll approve.

2018-02-27 22:08 UTC, ahmedtarek2134 commented
I changed the file now.

2018-03-01 19:40 UTC, merged